particle_filter:
  ros__parameters:
    num_particles: 500
    resample_threshold: 0.5
    map_yaml: maps/map.yaml
    odom_topic: /odom
    scan_topic: /scan
    particle_topic: /pf_particle_cloud
    publish_rate: 10.0
    beam_subsample: 10
    sigma_hit: 0.2
    z_hit: 0.8
    z_rand: 0.2
    z_max: 3.5
    alpha1: 0.02
    alpha2: 0.02
    alpha3: 0.02
    alpha4: 0.02
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    publish_tf: true
    initialization_mode: manual  # options: 'uniform', 'manual', 'odom'
    initial_pose_x: -2.0   # TurtleBot3 house spawn (see turtlebot3_house.launch.py)
    initial_pose_y: -0.5
    initial_pose_theta: 0.0
    initial_std_xy: 0.15
    initial_std_theta: 0.15
